/**
 * Builds the GameDistribution variant of the game.
 *
 *   node squash/build-gd.mjs --game-id=<YOUR GD GAME ID>
 *
 * Generated from squash/index.html rather than maintained by hand, so the
 * distributed build can never drift from the one that is tested. The output is
 * git-ignored: rebuild it, don't edit it.
 *
 * Why a separate build at all: the SDK is a third-party script that shows ads
 * and phones home. The repo's own copy stays a single self-contained file with
 * no network dependencies, which is what makes it trivially hostable anywhere
 * and honest to read. Only the copy uploaded to GameDistribution carries their
 * SDK.
 *
 * Integration follows their SDK Implementation guide:
 *   - window.GD_OPTIONS with gameId and an onEvent handler
 *   - SDK_GAME_PAUSE  -> pause AND mute (both are mandatory)
 *   - SDK_GAME_START  -> resume
 *   - gdsdk.showAd()  -> only ever from a user input event
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const gameId = (process.argv.find((a) => a.startsWith('--game-id=')) || '').split('=')[1];

if (!gameId) {
  console.error(
    'Usage: node squash/build-gd.mjs --game-id=<id>\n\n' +
    'The id comes from the GameDistribution developer portal after you create\n' +
    'the game entry there. Without it the SDK loads but reports nothing, so the\n' +
    'build refuses rather than producing something that silently earns nothing.',
  );
  process.exit(1);
}

const src = readFileSync(join(here, 'index.html'), 'utf8');

const sdk = `
<!-- ── GameDistribution SDK ────────────────────────────────────────────────
     Injected by build-gd.mjs. Do not edit this file; edit index.html and
     rebuild. See https://github.com/GameDistribution/GD-HTML5/wiki -->
<script>
window["GD_OPTIONS"] = {
  "gameId": ${JSON.stringify(gameId)},
  "onEvent": function (event) {
    switch (event.name) {
      case "SDK_GAME_PAUSE":
        // Their guide requires pausing AND muting. squashGame.pause() does
        // both, so an ad can never play over the sound of a rally.
        if (window.squashGame) window.squashGame.pause();
        break;
      case "SDK_GAME_START":
        if (window.squashGame) window.squashGame.resume();
        break;
      case "SDK_REWARDED_WATCH_COMPLETE":
        // The one signal that means the ad was genuinely watched through.
        // showAd('rewarded') also resolves, but their guide names this event
        // as the reward trigger, so it is what the promise below waits for.
        window.__gdRewardWatched = true;
        break;
    }
  }
};
(function (d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://html5.api.gamedistribution.com/main.js';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'gamedistribution-jssdk'));

/**
 * Ad breaks.
 *
 * Their guide is explicit that showAd() must be called from a user input
 * event, so these hang off real clicks — never off a timer or a game-state
 * change, which would be both against the rules and obnoxious.
 *
 * The two placements are the natural pauses a squash match already has: before
 * a tournament match begins, and between games within one. Nothing interrupts
 * a live rally.
 */
(function () {
  var showing = false;
  function ad() {
    if (showing) return;
    if (typeof gdsdk === 'undefined' || typeof gdsdk.showAd !== 'function') return;
    showing = true;
    try { gdsdk.showAd(); } catch (e) { /* never let an ad break the game */ }
    setTimeout(function () { showing = false; }, 1000);
  }

  /**
   * Rewarded ads.
   *
   * The game asks for a provider rather than calling the SDK itself, so the
   * repo build carries no ad code and never shows a "Watch ad" button it
   * cannot honour. Resolving true means watched to completion — their rules
   * are explicit that a dismissed or failed ad rewards nothing.
   */
  function rewarded() {
    return new Promise(function (resolve) {
      if (typeof gdsdk === 'undefined' || typeof gdsdk.showAd !== 'function') return resolve(false);
      window.__gdRewardWatched = false;
      gdsdk.showAd('rewarded')
        .then(function () { resolve(window.__gdRewardWatched === true); })
        .catch(function () { resolve(false); });
    });
  }

  document.addEventListener('DOMContentLoaded', function () {
    if (window.squashGame) window.squashGame.setRewardedAdProvider(rewarded);

    // Preloading is recommended, and a rewarded ad that takes five seconds to
    // appear after a deliberate tap reads as broken.
    if (typeof gdsdk !== 'undefined' && typeof gdsdk.preloadAd === 'function') {
      gdsdk.preloadAd('rewarded').catch(function () {});
    }

    var play = document.getElementById('tourPlay');
    if (play) play.addEventListener('click', ad);

    // Between games of a match: the scoreline has moved on, and the player is
    // about to serve the next game.
    var serve = document.getElementById('serveBtn');
    var lastGame = 1;
    if (serve) serve.addEventListener('click', function () {
      var s = window.__squash && window.__squash.state;
      if (s && s.gameNo > lastGame) { lastGame = s.gameNo; ad(); }
    });
  });
}());
</script>
`;

// Injected last so the game has defined window.squashGame before any SDK
// callback can fire.
const out = src.replace(/<\/script>\s*$/, '</script>\n' + sdk);
if (out === src) {
  console.error('Could not find the trailing </script> to inject after.');
  process.exit(1);
}

const dir = join(here, 'dist', 'gamedistribution');
mkdirSync(dir, { recursive: true });
writeFileSync(join(dir, 'index.html'), out);

// Zipped here rather than left as a manual step: the archive must have
// index.html at its root, and a zip of the *folder* (so every path is
// prefixed `gamedistribution/`) is rejected on upload.
const zip = join(here, 'dist', 'squash-gamedistribution.zip');
try {
  execFileSync('zip', ['-j', '-q', '-FS', zip, join(dir, 'index.html')]);
  console.log(`Built ${zip}`);
} catch {
  console.log(`Built ${join(dir, 'index.html')} — zip unavailable, archive it yourself`);
  console.log('index.html must sit at the ROOT of the archive, not inside a folder.');
}
console.log(`gameId ${gameId}`);
console.log('Upload the zip in the GameDistribution developer portal, UPLOAD tab.');
